[tool.ruff]
extend-select = ["C4", "SIM", "UP", "N", "D", "FBT", "COM", "T10", "ICN", "LOG", "G", "Q", "RET", "SLF", "TID", "TC", "ARG", "TRY", "FLY"]
ignore = []
show-fixes = true
target-version = "py311"