[[database]]
name = "my_db"
transient = false
owner = "ACCOUNTADMIN"
data_retention_time_in_days = 1
default_ddl_collation = "utf8"
log_level = "INFO"
object_id_tag = "792c2a9c-2812-39ed-99b4-1c182450260f"

[[database]]
name = "other_db"
owner = "ACCOUNTADMIN"
default_ddl_collation = "utf8"
object_id_tag = "030f119f-15af-3f80-a12c-87e923712acc"

