[[storage_integration]]
name = "example_storage_integration"
type = "external_stage"
owner = "<snowflake_role>"
storage_allowed_locations = [ "s3://example-bucket/", "s3://example-two-bucket/",]
enabled = true
storage_provider = "S3"
storage_aws_role_arn = "<iam_role>"
storage_aws_external_id = "<external_id>"
storage_aws_object_acl = "bucket-owner-full-control"
use_privatelink_endpoint = true
comment = "This is a storage integration comment"
object_id_tag = "a1b2c3d4-e5f6-7890-abcd-12345678efgh"

