[[view]]
name = "some_view"
secure = true
temporary = true
recursive = true
change_tracking = true
copy_grants = true
comment = "test"
object_id_tag = "5584fd16-b304-3399-85c4-ef63e0902888"
as_ = "select * from table"

